parameters:
  env(UP_TEST_CASE): ''
  UP_TEST_CASE: '%env(UP_TEST_CASE)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sandbox\AnApp\Service\APrivateService:

  Sandbox\AnApp\Service\APublicService:
    public: true
